### ISSUE TITLE
Question about structure

### ISSUE THREAD

**Issue by AlexKolykhalov** [Martina928/frontend-mentor-solutions#1]
Hi, can you tell me how to create a structure of repo like this (with folders)?

**Comment by Martina928** [comment]
> 
Hi,

1. Create a folder name frontend-mentor-solutions (or whatever you want)
    ```
    mkdir frontend-mentor-solutions
    ```
2. Into `frontend-mentor-solutions` folder and add version control

    ```
    cd frontend-mentor-solutions
    git init
    ```
3. Then, create the folders for each challenge in `frontend-mentor-solutions`, for example:

    ```
    mkdir 01-qr-code-component
    ```
4. Complete your solution in `01-qr-code-component` folder
5. After you finish git commit, add a new Github repo and push the whole folder in it

If I didn't explain it clear, please let me know!

**Comment by AlexKolykhalov** [comment]
Thank you very much, Martina!
I have one more question. Is any possibility to join all my repos causes frontend-mentor in one folder in GitHub or i must recreate all repos with new structure??
